# This is a basic workflow to help you get started with Actions

name: runTrades

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v3
      # setup python
      - name: setup python
        uses: actions/setup-python@v3
      # install dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install requests_html
          python -m pip install nums_from_string
          python -m pip install tweepy
          python -m pip install google_auth_oauthlib
          python -m pip install google-api-python-client
          python -m pip install newsapi-python
      # run file
      - name: execute trades
        run: |
          python main/Main_Actions.py
